[tool.poetry]
name = "portfolio_project"
version = "0.1.0"
description = ""
authors = ["SADATHRAHMANN <sadathrahman.n@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
